### ISSUE TITLE
Changes

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/groceristar#297]
# Description/Steps to reproduce

Hi @xy1994 xy1994, I prepared list with our changes, that we made to develop branch.
So we just need to move it to master and we'll be up to date.

copied;
_1 way:
a) you add pull request with your 4 commits to a master branch
b) then after my approve you'll checkout a brand-new develop branch - and we'll know that all things are up to date._

https://github.com/atherdon/groceristar/pull/220
https://github.com/atherdon/groceristar/pull/238/commits/19a998f376a261e833a78a939072df75fed3981a
https://github.com/atherdon/groceristar/pull/241/commits/7acfcd1c6d260a197828dc2ea8d2929917842b97
https://github.com/atherdon/groceristar/pull/242/commits/7388573f99ecf78b06fde2888edca848c657e27e
https://github.com/atherdon/groceristar/pull/231

DB changes: https://github.com/atherdon/groceristar/issues/290#issuecomment-343621478

https://github.com/atherdon/groceristar/issues/290#issuecomment-343622898
https://github.com/atherdon/groceristar/issues/290#issuecomment-343623563

# Expected result

# Additional information

**Comment by atherdon** [comment]
le'ts jump to this task @xy1994 
can you add
https://github.com/atherdon/groceristar/pull/238/commits/19a998f376a261e833a78a939072df75fed3981a
https://github.com/atherdon/groceristar/pull/241/commits/7acfcd1c6d260a197828dc2ea8d2929917842b97
https://github.com/atherdon/groceristar/pull/242/commits/7388573f99ecf78b06fde2888edca848c657e27e
from browser to master branch?

**Comment by yxie66** [comment]
done.

**Comment by atherdon** [comment]
Next is :
https://github.com/atherdon/groceristar/pull/220 
https://github.com/atherdon/groceristar/pull/231

**Comment by yxie66** [comment]
FB issue is already there in readme. Not sure whether I should add mlab tutorial via browser.

**Comment by atherdon** [comment]
So this changes are at readme in master, right?

**Comment by yxie66** [comment]
And I apologize for my slow progress, since I am very very busy this semester -- many courses together with job searching. Yes, it's already in the readme of your master branch

**Comment by atherdon** [comment]
All is fine, you don't need to ne worried. it's just live test about how you can handle this stresssful stuff.by my opinion you good. not sure if i was so good when i don't have working experience.

Ok, then let's finish this task too

- [x] import db logic to readme #255 
also from browser

**Comment by yxie66** [comment]
Thanks, I think I feel better now.
Db logic has been added on readme

**Comment by atherdon** [comment]
Do you have beer in your room? I think you'll need it soon :)

**Comment by yxie66** [comment]
hahaha, I think you are right!

**Comment by atherdon** [comment]
I'm not sure, but i don't see an explanation how to run migrate + import at readme. i think you add information about running import at heroku, but i mean local

also please check how readme looks on github - i think we loose some break-lines. Just check and make it looks better.
also readme title was not updated, so maybe you also miss something else at my commits, can you recheck, please?

![image](https://user-images.githubusercontent.com/1469198/32684985-8e24e40a-c69a-11e7-9197-a66331bdfc9c.png)

![image](https://user-images.githubusercontent.com/1469198/32684988-9b694034-c69a-11e7-93dc-d9ff7bd6a19f.png)
![image](https://user-images.githubusercontent.com/1469198/32684998-b0d92ed4-c69a-11e7-89ed-6c35824767f9.png)
![image](https://user-images.githubusercontent.com/1469198/32685002-b77d2768-c69a-11e7-8e41-c4c76fa0674b.png)

**Comment by yxie66** [comment]
Sure, hold on a moment.

The tutorial is about running on local, I just added heroku for later stage.

**Comment by atherdon** [comment]
it's good to have heroku - nice catch!

**Comment by yxie66** [comment]
I will add explanation to it.

**Comment by atherdon** [comment]
also check this part:
![image](https://user-images.githubusercontent.com/1469198/32685057-8883cfce-c69b-11e7-84b6-b94d68b2e5d2.png)

**Comment by yxie66** [comment]
done

**Comment by atherdon** [comment]
Check codacy button. not look very nice by my opinion.
also add first sentence about latest version at develop branch.

**Comment by yxie66** [comment]
hope it looks better.

**Comment by atherdon** [comment]
yeah, it does.
fix this: 
![image](https://user-images.githubusercontent.com/1469198/32685196-8b403ae8-c69d-11e7-8b33-58135d161a52.png)

and I'm still not sure where you put an explanation how to run **migrate** and **import** at local machine

**Comment by atherdon** [comment]
You need this: https://github.com/atherdon/groceristar/issues/252#issuecomment-340203757

and codacy button not working, so please remove current button and add a new one from this code.
`[![Codacy Badge](https://api.codacy.com/project/badge/Grade/76fe5b42fcc04691a06381ed1d26171b)](https://www.codacy.com/app/atherdon/loopback-fb-login?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=atherdon/loopback-fb-login&amp;utm_campaign=Badge_Grade)`

**Comment by yxie66** [comment]
The explanation is in the database logic part.
How do you want me to modify the first line?

**Comment by atherdon** [comment]
remove first line.

**Comment by atherdon** [comment]
Ok, i find it - my fault.
Can you add code wrapper for this two lines - because right now it's not easy to catch it by eye

**Comment by yxie66** [comment]
codacy is nice now.

**Comment by atherdon** [comment]
you need this: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by yxie66** [comment]
An excellent tutorial, thank you!

**Comment by atherdon** [comment]
we're pretty close to my beer :)

**Comment by atherdon** [comment]
ok, after finishing this last changes, jump to this issue: https://github.com/atherdon/groceristar/issues/298
